name: Deploy Nodejs app to EC2 server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Copy files to EC2
      - name: Copy files to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ubuntu
          REMOTE_PORT: 22
          SOURCE: "./"
          TARGET: "/home/ubuntu/node_Git_actions"

      # Step 2: Run docker on EC2
      - name: Execute remote commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/node_Git_actions
            docker compose down
            docker compose up -d --build